"""empty message

Revision ID: d5f29544900c
Revises: 0684a5a0ce02
Create Date: 2026-05-05 22:31:00.799982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5f29544900c'
down_revision: Union[str, Sequence[str], None] = '0684a5a0ce02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tamanhos', sa.Column('qtd_sabores', sa.Integer(), nullable=False, server_default='1'))
    # ### end Alembic commands ###

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tamanhos', 'qtd_sabores')
    # ### end Alembic commands ###
